name: Tilbakemelding
description: Meld om en feil eller foreslå en forbedring i Feltbok.
body:
  - type: textarea
    id: hva
    attributes:
      label: Tilbakemelding
      placeholder: "Jeg skulle ønske det var mulig å..."
    validations:
      required: false
  - type: textarea
    id: teknisk
    attributes:
      label: Tekniske detaljer
      description: "Fylles ut automatisk når du melder inn fra appen, la stå."
    validations:
      required: false
